sudo: false
dist: trusty
language: cpp

# Have to install g++7 to upgrade libstdc++

matrix:
  include:
    - os: osx
      osx_image: xcode10.1


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ctest -V
  - cd ..
  - ./runtests.sh
  - ! grep -q -B 14 -n -r /failed tests/system_tests/output/

notifications:
  email: false
